# Generated by Django 5.2.17 on 2026-09-30 08:20

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is taken. Please choose another.'}, help_text='Usernames are 3–30 characters: letters, numbers, dots, underscores or hyphens, starting with a letter or number.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Usernames are 3–30 characters: letters, numbers, dots, underscores or hyphens, starting with a letter or number.', regex='^[A-Za-z0-9][A-Za-z0-9._-]{2,29}$')], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='accounts_user_username_ci_unique'),
        ),
    ]
