# Generated by Django 5.2.17 on 2026-09-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyentry',
            name='amharic',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
