# Generated by Django 5.2.17 on 2026-09-30 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visitor_id', models.CharField(max_length=64)),
                ('session_id', models.CharField(help_text='A visit; a new one starts after 30 idle minutes.', max_length=64)),
                ('type', models.CharField(choices=[('session', 'Visit started'), ('view', 'Page view'), ('active', 'Active study minute'), ('grammar', 'Grammar quiz finished')], max_length=10)),
                ('unit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, choices=[('learn', 'Learn'), ('speak', 'Speak'), ('practice', 'Practice'), ('flashcards', 'Flashcards'), ('match', 'Match'), ('grammar', 'Grammar')], max_length=12)),
                ('scope', models.CharField(blank=True, help_text='Section or grammar lesson key.', max_length=60)),
                ('value', models.PositiveIntegerField(blank=True, help_text='Grammar quiz score.', null=True)),
                ('device', models.CharField(choices=[('phone', 'Phone / tablet'), ('desktop', 'Computer')], default='desktop', max_length=8)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visitor_id', 'created_at'], name='analytics_e_visitor_5129d6_idx'), models.Index(fields=['user', 'created_at'], name='analytics_e_user_id_9a87e5_idx')],
            },
        ),
    ]
