"""A picture for every vocabulary word that can be shown honestly, as emoji.

course_content.py turns each emoji into the file names of its Twemoji SVGs (static/course/pics/,
fetched by tools/fetch_word_pictures.py). Compound words get one picture per part, so learners see
how the word is built: der Apfelkuchen = '🍎+🍰'. Pictures without a + simply belong together
(die Großeltern = '👵👴').

Words without a clear picture (pronouns, articles, verb forms, most questions) are left out on
purpose: a forced picture teaches the wrong meaning.
"""

PICTURES = {
    # Start: sounds and numbers
    'der Mann': '👨', 'der Tee': '🍵', 'das Bett': '🛏️', 'rot': '🔴', 'gut': '🙂', 'die Mutter': '👩‍👧',
    'der Käse': '🧀', 'das Mädchen': '👧', 'schön': '🌸', 'hören': '👂', 'der Löffel': '🥄', 'die Tür': '🚪',
    'müde': '😴', 'Tschüss!': '👋', 'die Zeit': '⏳', 'die Liebe': '❤️', 'neu': '✨', 'die Häuser': '🏘️',
    'das Haus': '🏠', 'die Frau': '👩', 'das Wasser': '💧', 'der Wein': '🍷', 'der Vater': '👨‍👦',
    'die Zahl': '🔢', 'der Zug': '🚆', 'ja': '👍', 'nein': '👎', 'die Sonne': '☀️', 'die Straße': '🛣️',
    'gelb': '🟡', 'die Schule': '🏫', 'schnell': '🐇', 'sprechen': '🗣️', 'spielen': '🎲', 'die Stadt': '🏙️',
    'die Milch': '🥛', 'die Nacht': '🌙', 'das Buch': '📖', 'kochen': '🍳', 'der Apfel': '🍎', 'das Brot': '🍞',
    'eins': '1️⃣', 'zwei': '2️⃣', 'drei': '3️⃣', 'vier': '4️⃣', 'fünf': '5️⃣', 'sechs': '6️⃣', 'sieben': '7️⃣',
    'acht': '8️⃣', 'neun': '9️⃣', 'zehn': '🔟', 'hundert': '💯',
    'das Alphabet': '🔤', 'der Buchstabe': '🔤', 'buchstabieren': '🔤', 'der Name': '📛',
    'Wie ist Ihr Name, bitte?': '📛',

    # Unit 1: greetings, feelings, countries, languages
    'Hallo!': '👋', 'Hi!': '👋', 'Guten Tag!': '👋', 'Guten Morgen!': '🌅', 'Guten Abend!': '🌆',
    'Auf Wiedersehen!': '👋', 'der Morgen': '🌅', 'der Abend': '🌆', 'Gute Nacht!': '🌙',
    'Mein Name ist …': '📛', 'Ich weiß nicht.': '🤷',
    'Woher kommst du?': '🌍', 'Woher kommen Sie?': '🌍', 'Ich komme aus…': '🌍', 'Woher?': '🌍', 'Wo?': '📍',
    'aus den Vereinigten Staaten': '🇺🇸', 'aus der Schweiz': '🇨🇭', 'aus der Türkei': '🇹🇷',
    'aus den Niederlanden': '🇳🇱', 'aus den Vereinigten Arabischen Emiraten': '🇦🇪',
    'Ich komme aus den Vereinigten Staaten.': '🇺🇸',
    'sehr gut': '😀', 'schlecht': '🙁', 'sehr schlecht': '😫', 'soso': '😐', 'Super!': '👍', 'Es geht.': '😐',
    'Nicht so gut.': '😕', 'Auch gut.': '🙂', 'Mir geht es gut, danke. Und Ihnen?': '🙂', 'Freut mich!': '🤝',
    'danke / danke schön': '🙏', 'gern geschehen': '😊', 'Entschuldigung': '🙇', 'tut mir leid': '😔',
    'Äthiopien': '🇪🇹', 'Eritrea': '🇪🇷', 'Kenia': '🇰🇪', 'Deutschland': '🇩🇪', 'Österreich': '🇦🇹',
    'Frankreich': '🇫🇷', 'Spanien': '🇪🇸', 'Italien': '🇮🇹', 'Ich komme aus Äthiopien.': '🇪🇹',
    'Er kommt aus Kenia.': '🇰🇪', 'Sie kommt aus Eritrea.': '🇪🇷', 'Ich wohne in Addis Abeba.': '🇪🇹',
    'Ich lerne Deutsch.': '🇩🇪', 'der Deutschkurs': '🇩🇪', 'der Kursleiter': '👨‍🏫', 'die Kursleiterin': '👩‍🏫',
    'Ich verstehe das nicht.': '😕', 'Noch einmal, bitte.': '🔁', 'Langsam, bitte.': '🐢',
    'Entschuldigung, wie bitte?': '👂', 'Wie bitte?': '👂',

    # Unit 2: family and personal details
    'die Eltern': '👪', 'die Kinder': '👧👦', 'der Sohn': '👦', 'die Tochter': '👧', 'der Bruder': '👦',
    'die Schwester': '👧', 'die Geschwister': '👧👦', 'der Opa, der Großvater': '👴',
    'die Oma, die Großmutter': '👵', 'die Großeltern': '👵👴', 'mein Vater': '👨‍👦', 'meine Mutter': '👩‍👧',
    'meine Eltern': '👪', 'die Sprache': '🗣️', 'Welche Sprachen sprichst du?': '🗣️',
    'Deutsch': '🇩🇪', 'Englisch': '🇬🇧', 'Französisch': '🇫🇷', 'Spanisch': '🇪🇸', 'Portugiesisch': '🇵🇹',
    'Japanisch': '🇯🇵', 'Chinesisch': '🇨🇳', 'Amharisch': '🇪🇹', 'Tigrinya': '🇪🇷', 'Oromo': '🇪🇹',
    'Italienisch': '🇮🇹', 'Türkisch': '🇹🇷', 'Russisch': '🇷🇺', 'Ich spreche Deutsch.': '🇩🇪',
    'Ich spreche ein bisschen Englisch.': '🇬🇧', 'Sprichst du Englisch?': '🇬🇧',
    'Wie ist deine Telefonnummer?': '☎️', 'Wie lautet deine Telefonnummer?': '☎️', 'die Telefonnummer': '☎️',
    'Wo wohnst du?': '🏠', 'Wo wohnen Sie?': '🏠', 'Ich wohne in …': '🏠',
    'Bist du verheiratet?': '💍', 'Sind Sie verheiratet?': '💍', 'verheiratet': '💍', 'geschieden': '💔',
    'Ja, ich bin verheiratet.': '💍', 'Hast du Kinder?': '👧👦', 'Haben Sie Kinder?': '👧👦',
    'Ich habe einen Sohn.': '👦', 'Ich habe eine Tochter.': '👧', 'Ich habe zwei Kinder.': '👧👦',
    'der Freund': '🧑‍🤝‍🧑', 'die Freundin': '🧑‍🤝‍🧑',
    'die Handynummer': '📱', 'das Datum': '📅', 'die Unterschrift': '✍️', 'die Postleitzahl': '📮',
    'Wie alt bist du?': '🎂', 'Wie alt sind Sie?': '🎂', 'Ich bin 25 Jahre alt.': '🎂', 'das Alter': '🎂',
    'jung': '🧒', 'alt': '👴', 'Er ist 70 Jahre alt.': '👴',
    'der Enkel': '👦', 'die Enkelin': '👧', 'die Enkelkinder': '👧👦', 'der Ehemann': '🤵',
    'die Ehefrau': '👰', 'der Partner': '💑', 'die Partnerin': '💑', 'Mama': '👩‍👧', 'Papa': '👨‍👦',
    'das Kind': '🧒', 'Wir leben zusammen.': '👫', 'Ich lebe allein.': '🧍',

    # Unit 3: food and shopping
    'der Supermarkt': '🛒', 'der Laden': '🏪', 'das Geschäft': '🏪', 'einkaufen gehen': '🛍️',
    'kaufen': '🛍️', 'kosten': '🏷️', 'die Kartoffel': '🥔', 'die Tomate': '🍅', 'die Banane': '🍌',
    'der Saft': '🧃', 'die Birne': '🍐', 'die Orange': '🍊', 'die Erdbeere': '🍓', 'die Traube': '🍇',
    'der/die Paprika': '🫑', 'die Gurke': '🥒', 'die Zwiebel': '🧅', 'ein Apfel': '🍎', 'eine Banane': '🍌',
    'die Nahrungsmittel': '🛒', 'der Kuchen': '🍰', 'das Ei': '🥚', 'der Reis': '🍚', 'das Fleisch': '🥩',
    'der Fisch': '🐟', 'die Wurst': '🌭', 'Hast du Hunger?': '🍽️', 'Ich habe Hunger.': '🍽️',
    'Guten Appetit!': '🍽️', 'Ich möchte kein Stück Kuchen.': '🍰',
    'das Bier': '🍺', 'das Mineralwasser': '💧', 'der Kaffee': '☕', 'der Orangensaft': '🍊+🧃',
    'Hast du Durst?': '🥤', 'Bist du durstig?': '🥤', 'Ich habe Durst.': '🥤',
    'Was möchtest du trinken?': '🥤', 'Was möchten Sie trinken?': '🥤', 'Schmeckt gut!': '😋', 'Prost!': '🍻',
    'Wie viel kostet das?': '💶', 'Was kostet das?': '💶', 'Das kostet …': '💶', 'Das macht …': '💶',
    'der Preis': '🏷️', 'der Euro': '💶', 'der Cent': '🪙', 'das Kilo': '⚖️', 'das Wechselgeld': '🪙',
    'Isst du gerne Fisch?': '🐟', 'Trinkst du gerne Tee?': '🍵', 'Ja, ich esse gerne Fisch.': '🐟',
    'Nein, ich trinke nicht gerne Tee.': '🍵', 'Was ist dein Lieblingsessen?': '❤️+🍽️',
    'Was isst du gerne?': '🍽️', 'Was trinkst du gerne?': '🥤', 'essen': '🍽️',
    'etwas zum Trinken': '🥤', 'etwas zum Essen': '🍽️', 'Können wir bitte die Rechnung bekommen?': '🧾',
    'Zahlen Sie mit Karte oder Bargeld?': '💳', 'Stimmt so.': '🪙', 'der Kellner': '🤵', 'die Gäste': '👥',
    'ein Glas Wein': '🍷', 'die Speise, das Essen': '🍽️', 'die Getränke': '🥤',
    'der Nachtisch, die Nachspeise': '🍮', 'die Rechnung': '🧾', 'köstlich': '😋', 'das Bargeld': '💵',
    'die Kreditkarte': '💳', 'das Trinkgeld': '🪙',
    'Ich mag Kaffee.': '☕', 'Ich mag keinen Fisch.': '🐟', 'lecker': '😋', 'Das schmeckt gut.': '😋',
    'das Frühstück': '🍳', 'zum Frühstück': '🍳', 'Was isst du zum Frühstück?': '🍳', 'das Abendessen': '🍽️',
    'das Müsli': '🥣', 'die Marmelade': '🍓🫙', 'der Honig': '🍯', 'die Butter': '🧈', 'die Suppe': '🍲',
    'der Salat': '🥗', 'die Nudeln': '🍝', 'das Eis': '🍦', 'die Tasse': '☕', 'eine Tasse Kaffee': '☕',
    'der Apfelkuchen': '🍎+🍰', 'der Apfelsaft': '🍎+🧃', 'der Schokoladenkuchen': '🍫+🍰',
    'die Kartoffelsuppe': '🥔+🍲', 'die Tomatensuppe': '🍅+🍲', 'das Käsebrot': '🧀+🍞', 'der Obstsalat': '🍓+🥗',
    'die Kaffeetasse': '☕',

    # Unit 4: home and living
    'die Wohnung': '🏢', 'das Zimmer': '🚪', 'das Wohnzimmer': '🛋️', 'das Schlafzimmer': '🛏️',
    'das Kinderzimmer': '🧸', 'das Arbeitszimmer': '🖥️', 'die Küche': '🍳', 'das Badezimmer': '🛁',
    'das Bad': '🛁', 'Entschuldigung, wo ist das Badezimmer?': '🛁', 'Wo ist es?': '📍',
    'links': '⬅️', 'rechts': '➡️', 'teuer': '💰', 'hässlich': '🤢', 'dunkel': '🌑', 'hell': '💡',
    'klein': '🐭', 'groß': '🐘', 'Das Auto ist nicht neu.': '🚗', 'Das ist doch toll!': '🤩',
    'der Garten': '🏡', 'die Garage': '🚗',
    'das Sofa': '🛋️', 'die Couch': '🛋️', 'der Stuhl': '🪑', 'der Fernseher': '📺', 'die Lampe': '💡',
    'Es gefällt mir.': '👍', 'Es gefällt mir sehr.': '👍', 'Es gefällt mir sehr gut.': '👍',
    'Es gefällt mir nicht.': '👎', 'Es gefällt mir nicht so gut.': '👎', 'Es gefällt mir überhaupt nicht.': '👎',
    'die Spüle': '🚰', 'die Dusche': '🚿', 'die Badewanne': '🛁', 'der Spiegel': '🪞', 'die Toilette': '🚽',
    'weiß': '⚪', 'schwarz': '⚫', 'blau': '🔵', 'grün': '🟢', 'orange': '🟠', 'braun': '🟤', 'lila': '🟣',
    'Welche Farbe hat …?': '🎨', 'Welche Farbe haben …?': '🎨',
    'der Kugelschreiber': '🖊️', 'der Kuli': '🖊️', 'der Bleistift': '✏️', 'die Brille': '👓', 'das Heft': '📓',
    'die Kamera': '📷', 'die Kette': '📿', 'der Schlüssel': '🔑', 'die Tasche': '👜', 'das Handy': '📱',
    'der Regenschirm': '☂️', 'Das ist ein Schlüssel.': '🔑',
    'das Holz': '🪵', 'das Papier': '📄', 'das Metall': '🔩', 'der Stoff': '🧵', 'aus Holz': '🪵',
    'Die Tasche ist aus Leder.': '👜',
    'Kein Problem.': '👌', 'Sehr gern.': '😊', 'die E-Mail-Adresse': '📧', 'Wie ist deine E-Mail-Adresse?': '📧',
    'das Sonderangebot': '🏷️', 'Schau mal!': '👀', 'Wie findest du das Sofa?': '🛋️',
    'Wie viel kostet der Stuhl?': '🪑', 'Er kostet 59 Euro.': '💶',

    # Unit 5: daily routine and time
    'die Uhr': '🕰️', 'die Zähne': '🦷', 'die Arbeit': '💼', 'arbeiten': '💼', 'aufräumen': '🧹',
    'das Mittagessen': '🍽️', 'fernsehen': '📺', 'trinken': '🥤', 'das Computerspiel': '🎮', 'schlafen': '😴',
    'Es ist 8 Uhr.': '🕗', 'sich die Zähne putzen': '🪥', 'sich anziehen': '👕', 'zur Arbeit fahren': '🚌',
    'nach Hause kommen': '🏠', 'schlafen gehen': '🛌',
    'Wie spät ist es?': '🕰️', 'Wie viel Uhr ist es?': '🕰️', 'Es ist neun Uhr.': '🕘', 'Es ist ein Uhr.': '🕐',
    'Es ist halb zwei.': '🕜', 'Es ist halb zehn.': '🕤', 'um acht Uhr': '🕗', 'Um wie viel Uhr?': '🕰️',
    'aufstehen': '⏰', 'anrufen': '📞', 'anziehen': '👕', 'einkaufen': '🛍️', 'aufmachen': '🔓',
    'zumachen': '🔒', 'Ich stehe um 7 Uhr auf.': '⏰',
    'Kochst du gerne?': '🍳', 'Kaufst du gerne ein?': '🛍️', 'Er spielt gerne Gitarre.': '🎸',
    'Ich mache nicht gerne Kuchen.': '🍰',
    'der Frühling': '🌷', 'der Sommer': '🌻', 'der Herbst': '🍂', 'der Winter': '⛄', 'die Monate': '📅',
    'die Jahreszeiten': '🌷🍂',
    'der Geburtstag': '🎂', 'beginnen': '🏁', 'fragen': '❓', 'pünktlich': '⏱️', 'toll': '🤩',
    'Zeit haben': '⏳', 'eine Party machen': '🎉', 'Sei pünktlich!': '⏱️', 'Bis Samstag!': '👋',
    'waschen': '🧼', 'fahren': '🚗', 'geben': '🎁', 'lesen': '📖', 'sehen': '👀',
    'der Mittag': '🕛', 'am Morgen': '🌅', 'am Abend': '🌆', 'in der Nacht': '🌙', 'heute Abend': '🌆',
    'morgen früh': '🌅',
    'das Kino': '🎬', 'das Museum': '🏛️', 'das Theater': '🎭', 'das Café': '☕', 'das Konzert': '🎶',
    'das Restaurant': '🍽️', 'das Fitnessstudio': '🏋️', 'die Bar': '🍸', 'ins Kino gehen': '🎬',
    'ins Konzert gehen': '🎶', 'spazieren gehen': '🚶',
    'Gehen wir ins Kino?': '🍿', 'Lust auf Kaffee?': '☕', 'Gute Idee!': '💡', 'Ja, gern.': '👍',
    'Vielleicht.': '🤔', 'Tut mir leid, ich kann leider nicht.': '😔', 'Bis dann!': '👋',
    'Hast du am Samstag Zeit?': '📅', 'Weißt du, wo das Kino ist?': '🎬',

    # Unit 6: weather, holidays and hobbies
    'das Wetter': '🌦️', 'der Regen': '🌧️', 'der Schnee': '❄️', 'warm': '🌤️', 'heiß': '🥵', 'kalt': '🥶',
    'es regnet': '🌧️', 'es schneit': '🌨️', 'die Sonne scheint': '☀️', 'es ist sonnig': '☀️',
    'Wie ist das Wetter?': '🌦️', 'Es ist 20 Grad.': '🌡️',
    'die Wolke': '☁️', 'wolkig': '☁️', 'der Wind': '💨', 'windig': '💨', 'der Nebel': '🌫️',
    'das Gewitter': '⛈️', 'die Temperatur': '🌡️', 'das Grad': '🌡️',
    'der Norden': '⬆️', 'der Süden': '⬇️', 'der Osten': '➡️', 'der Westen': '⬅️',
    'der Urlaub': '🏖️', 'das Zelt': '⛺', 'das Meer': '🌊', 'die Küste': '🏝️', 'schwimmen': '🏊',
    'schnorcheln': '🤿', 'tauchen': '🤿', 'das Skifahren': '⛷️', 'das Schlittschuhlaufen': '⛸️',
    'die Natur': '🏞️', 'wandern': '🥾', 'Urlaub machen': '🏖️',
    'tanzen': '💃', 'reisen': '🧳', 'joggen': '🏃', 'malen': '🎨', 'die Fotografie': '📸',
    'Fahrrad fahren': '🚴', 'Freunde treffen': '🧑‍🤝‍🧑', 'Computerspiele spielen': '🎮', 'Musik hören': '🎧',
    'Musik machen': '🎶', 'Fußball spielen': '⚽', 'Basketball spielen': '🏀', 'Handball spielen': '🤾',
    'die Tennisschuhe': '👟', 'das Fahrrad': '🚲', 'das Schwimmbad': '🏊', 'die Badehose': '🩳',
    'der Badeanzug': '🩱', 'die Jacke': '🧥', 'die Mütze': '🧢',
    'der Lieblingsfilm': '❤️+🎬', 'das Lieblingsbuch': '❤️+📖', 'die Lieblingsmusik': '❤️+🎵',
    'das Lieblingslied': '❤️+🎵', 'das Lieblingsessen': '❤️+🍽️', 'das Lieblingsgetränk': '❤️+🥤',
    'die Lieblingsfarbe': '❤️+🎨',
    'kompliziert': '🧩', 'langweilig': '🥱', 'freundlich': '😊', 'nett': '😊',
    'Das stimmt.': '✅', 'Das stimmt nicht.': '❌', 'Das ist richtig.': '✅', 'Das ist nicht richtig.': '❌',
    'Genau.': '🎯',
    'Du kannst toll tanzen!': '💃', 'Sie können super kochen!': '👩‍🍳', 'Vielen Dank!': '🙏',
    'Herzlichen Dank!': '🙏', 'Ich finde das toll.': '🤩', 'Ich finde das lustig.': '😂',
    'Ich finde das komisch.': '🤨', 'Ich finde das blöd.': '🙄', 'Das macht Spaß.': '😄',
    'singen': '🎤', 'backen': '🧁', 'reiten': '🏇', 'fotografieren': '📸', 'Schach spielen': '♟️',
    'Ski fahren': '⛷️', 'Rad fahren': '🚴', 'Tennis spielen': '🎾', 'Mein Hobby ist Lesen.': '📚',
    'Ich lese gern.': '📚',

    # Unit 7: jobs and abilities
    'der Lehrer': '👨‍🏫', 'die Lehrerin': '👩‍🏫', 'der Ingenieur': '👷‍♂️', 'die Ingenieurin': '👷‍♀️',
    'der Verkäufer': '🛍️', 'die Verkäuferin': '🛍️', 'die Kellnerin': '🍽️', 'der Programmierer': '👨‍💻',
    'die Programmiererin': '👩‍💻', 'der Polizist': '👮‍♂️', 'die Polizistin': '👮‍♀️', 'der Elektriker': '🔌',
    'die Elektrikerin': '🔌', 'der Journalist': '📰', 'die Journalistin': '📰', 'der Mechaniker': '👨‍🔧',
    'die Mechanikerin': '👩‍🔧', 'der Arzt': '👨‍⚕️', 'die Ärztin': '👩‍⚕️', 'der Krankenpfleger': '🏥',
    'die Krankenschwester': '🏥', 'der Tierarzt': '🐾', 'die Tierärztin': '🐾', 'der Zahnarzt': '🦷',
    'die Zahnärztin': '🦷', 'der Geschäftsmann': '👨‍💼', 'die Geschäftsfrau': '👩‍💼', 'der Anwalt': '⚖️',
    'die Anwältin': '⚖️', 'der Friseur': '💈', 'die Friseurin': '💈', 'der Koch': '👨‍🍳', 'die Köchin': '👩‍🍳',
    'Ich bin Lehrerin von Beruf.': '👩‍🏫',
    'Sie kann sehr gut tanzen.': '💃', 'Skateboard fahren': '🛹', 'Ski laufen': '⛷️', 'Gitarre spielen': '🎸',
    'die Aussprache': '🗣️', 'das Hörverstehen': '👂', 'das Vokabular': '📚',
    'der Empfänger': '📥', 'der Absender': '📤', 'der Anhang': '📎', 'senden': '📤', 'löschen': '🗑️',
    'schreiben': '✍️', 'Liebe Grüße': '💌',
    'hat gegessen': '🍽️', 'hat gefunden': '🔍', 'hat geschrieben': '✍️', 'hat gesprochen': '🗣️',
    'hat getroffen': '🤝', 'hat getrunken': '🥤', 'ist gegangen': '🚶', 'ist gefahren': '🚗',
    'ist gereist': '🧳',
    'Ich arbeite als Krankenpfleger.': '🏥', 'Ich arbeite bei Ethiopian Airlines.': '✈️',
    'Ich studiere Medizin.': '🩺', 'der Student': '👨‍🎓', 'die Studentin': '👩‍🎓', 'der Rentner': '👴',
    'die Rentnerin': '👵',
    'der Computer': '🖥️', 'der Laptop': '💻', 'der Drucker': '🖨️', 'die Maus': '🖱️', 'die Tastatur': '⌨️',
    'der Bildschirm': '🖥️', 'das Passwort': '🔐', 'die Nachricht': '💬', 'der Termin': '📅',
    'der Kalender': '📅', 'der Stift': '🖊️', 'das WLAN': '📶', 'die Visitenkarte': '📇',
    'Ich brauche einen Stift.': '🖊️',
    'Einen Moment, bitte.': '⏳', 'Auf Wiederhören!': '📞', 'telefonieren': '📞',

    # Unit 8: travel and transport
    'der Bus': '🚌', 'die U-Bahn': '🚇', 'die S-Bahn': '🚆', 'die Straßenbahn': '🚋', 'das Taxi': '🚕',
    'das Auto': '🚗', 'das Flugzeug': '✈️', 'mit dem Bus': '🚌', 'mit dem Zug': '🚆', 'mit der U-Bahn': '🚇',
    'zu Fuß': '🚶',
    'der Bahnhof': '🚉', 'der Hauptbahnhof': '🚉', 'der Flughafen': '🛫', 'die Haltestelle': '🚏',
    'das Gleis': '🛤️', 'der Bahnsteig': '🚉', 'die Fahrkarte': '🎫', 'der Flug': '✈️', 'die Verspätung': '⌛',
    'die Abfahrt': '🛫', 'die Ankunft': '🛬',
    'das Gepäck': '🧳', 'der Koffer': '🧳', 'der Rucksack': '🎒', 'der Pass': '🛂', 'das Visum': '🛂',
    'der Akku': '🔋', 'das Ladegerät': '🔌',
    'abfliegen': '🛫', 'fliegen': '✈️', 'landen': '🛬',
    'Wann kommst du an?': '🛬', 'Wann fliegst du ab?': '🛫', 'Kannst du mich abholen?': '🚗',
    'Natürlich hole ich dich ab.': '🚗', 'Hoffentlich haben wir keine Verspätung.': '⌛',
    'Ich freue mich auf dich!': '🤗', 'Alles klar!': '👌', 'Gute Reise!': '🧳',
    'Achtung!': '⚠️', 'Bitte Vorsicht!': '⚠️', 'Der Zug fährt von Gleis 4 ab.': '🚆',
    'Das Flugzeug landet um 6:40 Uhr.': '🛬',

    # Unit 9: yesterday and last year
    'Ich habe gearbeitet.': '💼', 'Ich habe eingekauft.': '🛍️', 'Ich habe gekocht.': '🍳',
    'Ich habe Kaffee getrunken.': '☕', 'Ich habe ein Buch gelesen.': '📖', 'Ich habe ferngesehen.': '📺',
    'Ich habe aufgeräumt.': '🧹', 'Ich habe lange geschlafen.': '😴', 'Ich habe telefoniert.': '📞',
    'Ich habe fotografiert.': '📸', 'Ich habe Freunde getroffen.': '🧑‍🤝‍🧑',
    'Ich bin nach Hause gegangen.': '🏠', 'Ich bin nach Hawassa gefahren.': '🚌',
    'Ich bin nach Rom geflogen.': '✈️', 'Ich bin zu Hause geblieben.': '🏠', 'Ich bin gelaufen.': '🏃',
    'Ich hatte Glück mit dem Wetter.': '🍀', 'Wir hatten viel Spaß.': '😄',
    'die Öffnungszeiten': '🕘', 'geöffnet': '🔓', 'geschlossen': '🔒', 'die Praxis': '🩺', 'die Bank': '🏦',
    'die Apotheke': '💊',
    'das Fest': '🎉', 'feiern': '🥳', 'Weihnachten': '🎄', 'Silvester': '🎆', 'Ostern': '🐣',
    'das Neujahr': '🎊', 'Wann hast du Geburtstag?': '🎂', 'Ich habe im März Geburtstag.': '🎂',
    'nach Deutschland': '🇩🇪', 'in die Schweiz': '🇨🇭', 'eine Reise machen': '🧳',
    'Freunde besuchen': '🧑‍🤝‍🧑',
}
